# template-terraform-module

Terraform module template following [Standard Module Structure](https://www.terraform.io/docs/modules/create.html#standard-module-structure).

## Usage

Named `terraform-<PROVIDER>-<NAME>`. Module repositories must use this three-part name format.


## Examples

- [Minimal](https://github.com/tmknom/template-terraform-module/tree/master/examples/minimal)
- [Complete](https://github.com/tmknom/template-terraform-module/tree/master/examples/complete)

<!-- BEGINNING OF GENERATED BY TERRAFORM-DOCS -->

## Requirements

Write your Terraform module requirements.

## Providers

Write your Terraform module providers.

## Inputs

Write your Terraform module inputs.

## Outputs

Write your Terraform module outputs.

<!-- END OF GENERATED BY TERRAFORM-DOCS -->

## Development

### Development Requirements

- [Docker](https://www.docker.com/)

### Configure environment variables

```shell
export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export AWS_DEFAULT_REGION=ap-northeast-1
```

### Installation

```shell
git clone git@github.com:tmknom/template-terraform-module.git
cd template-terraform-module
make install
```

### Makefile targets

```text
apply-complete                 Run terraform apply examples/complete
apply-minimal                  Run terraform apply examples/minimal
check-format                   Check format code
clean                          Clean .terraform
destroy-complete               Run terraform destroy examples/complete
destroy-minimal                Run terraform destroy examples/minimal
diff                           Word diff
docs                           Generate docs
format                         Format code
help                           Show help
install                        Install requirements
lint                           Lint code
plan-complete                  Run terraform plan examples/complete
plan-minimal                   Run terraform plan examples/minimal
release                        Release GitHub and Terraform Module Registry
upgrade                        Upgrade makefile
```

### Releasing new versions

Bump VERSION file, and run `make release`.

### Terraform Module Registry

- <https://registry.terraform.io/modules/tmknom/name/provider>

## License

Apache 2 Licensed. See LICENSE for full details.